### ISSUE TITLE
Implement dark mode for web console

### ISSUE THREAD

**Issue by Tronic** [PurpleI2P/i2pd#1699]
The bright white background is very bad on OLED displays now popular in both mobile and desktop use. Also the bright white burns my eyeballs even in daytime use, even more so in night use. Pretty much all web services now offer a dark mode, which I suggest should be implemented for i2pd web console as well.

Basically you want something like this:
```css
@media (prefers-color-scheme: dark) {
  body { background: #444; color: #ddd; }
  h1, h2, h3 { color: #fff; }
  a { color: #88f; }
  input, button, textarea { background: #000; color: #ddd; }
}
```

This simple change of CSS is all you need to support both the light (default) and the dark modes as per the user's desktop settings. It needs a bit more tuning possibly for some `input` and `a` types, but it is really not much work, and won't affect those users who have not set their system to use the dark theme.

Thanks!
