### ISSUE TITLE
NAT Failure leaking private docker IP address

### ISSUE THREAD

**Issue by tril0byte** [PurpleI2P/i2pd#1859]
The docker container i2p is occasionally leaking packets with source IP of Private Net-10 address into the Internet. Firewall is dropping them because they do not correspond to any existing connection. I have 3 example packet captures.  

ethertype IPv4 (0x0800), length 66: (tos 0x0, ttl 63, id 47094, offset 0, flags [DF], proto TCP (6), length 52)
    10.21.21.15.40758 > 82.69.81.175.24490: Flags [F.], cksum 0x6172 (correct), seq 3575027993, ack 3840936104, win 502, options [nop,nop,TS val 293107033 ecr 1460410292], length 0

ethertype IPv4 (0x0800), length 54: (tos 0x0, ttl 63, id 61860, offset 0, flags [DF], proto TCP (6), length 40)
    10.21.22.11.48516 > 61.69.250.79.30341: Flags [F.], cksum 0x7aa1 (correct), seq 1602524572, ack 67022430, win 502, length 0

ethertype IPv4 (0x0800), length 54: (tos 0x0, ttl 63, id 0, offset 0, flags [DF], proto TCP (6), length 40)
    10.21.21.15.39226 > 73.228.103.252.20211: Flags [R], cksum 0x5eca (correct), seq 1441350139, win 0, length 0

10.21.21.15 is Citadel using
image: purplei2p/i2pd:latest@sha256:d8e1a28a8428ed9bda15bbf773e355cf46c89c652dcaa6cd9131606ee308ae47

 10.21.22.11 is Umbrel using
image: purplei2p/i2pd:release-2.44.0@sha256:d154a599793c393cf9c91f8549ba7ece0bb40e5728e1813aa6dd4c210aa606f6

Most of the packets are normally SRC-NAT to the IP of the machine running docker which is 192.168.x.x so these packets with source IP 10.y.y.y should never appear on this network

**Comment by tril0byte** [comment]
most recent docker version of machine affected below, the others are older.

citadel# docker version
Client: Docker Engine - Community
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 18:02:28 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       3056208
  Built:            Tue Oct 25 18:00:19 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.12
  GitCommit:        a05d175400b1145e5e6a735a6710579d181e7fb0
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by tril0byte** [comment]
/home/citadel/citadel/docker-compose.yml:

```
  i2p:
    container_name: i2p
    user: 1000:1000
    image: purplei2p/i2pd:latest@sha256:d8e1a28a8428ed9bda15bbf773e355cf46c89c652dcaa6cd9131606ee308ae47
    working_dir: /data
    volumes:
    - ${PWD}/i2p:/home/i2pd/data
    restart: on-failure
    stop_grace_period: 1m
    init: true
    networks:
      default:
        ipv4_address: $I2P_IP
```

/home/umbrel/umbrel/app-data/bitcoin/docker-compose.yml:
```i2pd_daemon:
    image: purplei2p/i2pd:release-2.44.0@sha256:d154a599793c393cf9c91f8549ba7ece0bb40e5728e1813aa6dd4c210aa606f6
    user: "root"
    command: --sam.enabled=true --sam.address=0.0.0.0 --sam.port=7656 --loglevel=error
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/i2pd:/home/i2pd/data
    networks:
      default:
        ipv4_address: "${APP_BITCOIN_I2P_DAEMON_IP}"
```
